#create variable to hold DNA sequence as string
DNA = 'GATGGGATTggggttttccccTCCCATGTGCTCAAGACTGGCGCTaaaaGttttGAGCTTCTCaaaaGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCggggACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGccccCTCTGAGTCAGGAAACAttttCAGACCTATGGAAACTACTTCCTGaaaaCAACGTTCTGTccccCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTccccGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTccccCCGTGGccccTGCACCAGCAGCTCCTACACCGGCGGccccTGCACCAGccccCTCCTGGccccTGTCATCTTCTGTCCCTTCCCAGaaaaCCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTccccTGCCCTCAACAAGATGttttGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACAccccCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGccccCACCATGAGCGCT'
#make the cases the same
#DNA_low = DNA.lower()
#print(DNA_low)
#replace nucletoides with complements
DNA_comp_a = DNA.replace('a','t')
print(DNA_comp_a)
DNA_comp_A = DNA.replace('A','T')
print(DNA_comp_A)
DNA_comp_T = DNA_comp_A.replace('t', 'A')
print(DNA_comp_T)
DNA_comp_G = DNA_comp_T.replace('g','C')
print(DNA_comp_G)
DNA_comp_C = DNA_comp_G.replace('c', 'G')
#final version of fwd seqence
print(DNA_comp_C)
#reverse reverse!!
print(f' reverse transcription {DNA_comp_C[::-1]}')